name: chat_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  emoji_picker_flutter: ^4.3.0
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.14.3
  fluttertoast: ^8.2.12
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  nested: ^1.0.0
  path_provider: ^2.1.5
  provider: ^6.1.5
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - assets/fonts/Inter_18pt-Regular.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/
  filename: assets.dart
  field_prefix: null
